### ISSUE TITLE
Cut the WF prefix with NS_SWIFT_NAME

### ISSUE THREAD

**Issue by conradev** [DeskConnect/WFOAuth2#2]

**Comment by AriX** [comment]
I think we should very carefully consider whether this is something we should be doing, both inside Workflow and outside. I'm not sure it's actually currently in the spirit of Swift to do so (especially for third-party libraries) given the lack of real namespacing and the fact that Apple system libraries retain their prefixes. This morning, I read through the entirety of the Swift Evolution postings on the `NS` prefix dropping proposal to better understand what the goals are, and rationale behind the prefix dropping was pretty specifically because some Foundation classes are meant to be thought of as core Swift classes.

Also note that the stated purpose for `NS_SWIFT_NAME` on the Swift blog is as follows:

> Specific Objective-C APIs that translate poorly into Swift will then be annotated (for example, with `NS_SWIFT_NAME`) to improve the resulting Swift code.

(That is, `NS_SWIFT_NAME` is primarily intended to improve the names of things; it's not recommended anywhere that it be used to drop class prefixes.)
